# 以下配置需放在bootstrap中，因为加载顺序: bootstrap > config配置中心 > application
server:
  port: 8080
  address: 192.168.56.42
spring:
  profiles:
    active: dev
  cloud:
    consul:
      host: 192.168.56.42
      port: 8500
      discovery:
        health-check-interval: 15s
    gateway: # https://cloud.spring.io/spring-cloud-static/spring-cloud-gateway/2.0.2.RELEASE/single/spring-cloud-gateway.html
      discovery:
        locator:
          enabled: true
      routes:
        - id: hello
          uri: lb://HelloService
          predicates:
            - Path=/hello/**
          filters:
            - StripPrefix=1
        - id: order
          uri: lb://OrderService
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
