server:
  port: 8080
spring:
  application:
    name: OrderService
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        health-check-interval: 15s
    config:
      uri: http://loaclhost:8001
      profile: dev
      label: master